#creating a tuple using()
t=(1,2,3,5,5,6,6,5,5,6,8,5,7,7)
print(t.count(5))
t1=(7,0,8,0,0,9)
print(t1.count(0))
print(t.index(5))
'''taking input from user and preparing fruit list'''
f1=input("enter fruit number 1 ")
f2=input("enter fruit number 2 ")
f3=input("enter fruit number 3 ")
f4=input("enter fruit number 4 ")
f5=input("enter fruit number 5 ")
f6=input("enter fruit number 6 ")
f7=input("enter fruit number 7 ")
myfruitlist=[f1,f2,f3,f4,f5,f6,f7]
print(myfruitlist)
